name: building .net application
on:
    push:

jobs:
    build_dot_net:
        runs on: ubuntu-latest
        steps:
        - name: setup dotnet sdk
        - uses: actions/checkout@v3
        - uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '36.0.x'
        - run: dotnet build <my project>

        - name: checkout your source