name: building .net application
on:
    push:

jobs:
    build_dot_net:
        runs on: ubuntu-latest

        steps:
        - name: setup dotnet sdk
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '6.0.x'

        - name: checkout
          uses: actions/checkout@v3

        - name: list your repo before build
          run: ls - l
        
        - name: build app
          run: dotnet build
        
        - name: list files after biild
          run: ls - lR TicTacToe/bin     